# Default values for keycloak

replicaCount: 1

image:
  repository: quay.io/keycloak/keycloak
  tag: 24.0.1
  pullPolicy: IfNotPresent

command: ["start-dev", "--import-realm"]

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

name: keycloak

admin:
  username: admin
  password: admin


database:
  enabled: true
  name: keycloak-mysql
  provider: mysql
  image:
    repository: mysql
    tag: 8.3.0
    pullPolicy: IfNotPresent
  service:
    port: 3306
  auth:
    rootPassword: root
    database: keycloak
    username: keycloak
    password: password
  persistence:
    enabled: true
    storageClass: ""
    accessMode: ReadWriteOnce
    size: 8Gi
    mountPath: /var/lib/mysql

# ConfigMap for Keycloak configuration
configmap:
  name: keycloak-config

# Volume for importing realms
volumes:
  realms:
    enabled: true
    mountPath: /opt/keycloak/data/import/
    configmapName: keycloak-realms