8081apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-config
data:
  # Application Configuration
  APP_NAME: "inventory-service"
  SERVER_PORT: {{ .Values.app.containerPort | quote }}
  VIRTUAL_THREADS_ENABLED: "true"

  # Database Configuration
  SPRING_DATASOURCE_URL: "jdbc:mysql://{{ .Values.mysql.host }}:{{ .Values.mysql.servicePort }}/{{ .Values.mysql.database }}"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_DATASOURCE_PASSWORD: {{ .Values.mysql.rootPassword | quote }}
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "com.mysql.cj.jdbc.Driver"

  # JPA Configuration
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"

  # Flyway Configuration
  SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
  SPRING_FLYWAY_LOCATIONS: "classpath:db/migration"

  # Documentation Configuration
  SPRINGDOC_SWAGGER_UI_PATH: "/swagger-ui.html"
  SPRINGDOC_API_DOCS_PATH: "/v1/api-docs"
  DOCS_TITLE: "Inventory Service"
  DOCS_VERSION: "1.0"

  # Kafka Configuration
  SPRING_KAFKA_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  SPRING_KAFKA_PRODUCER_KEY_SERIALIZER: "org.apache.kafka.common.serialization.StringSerializer"
  SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER: "io.confluent.kafka.serializers.KafkaAvroSerializer"
  SPRING_KAFKA_PRODUCER_PROPERTIES_SCHEMA_REGISTRY_URL: {{ .Values.schemaRegistry.url | quote }}
  SPRING_KAFKA_CONSUMER_GROUP_ID: "inventory-Service"
  SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER: "org.apache.kafka.common.serialization.StringDeserializer"
  SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER: "org.springframework.kafka.support.serializer.ErrorHandlingDeserializer"

  # Monitoring Configuration
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: {{ .Values.monitoring.sampling.probability | quote }}
