apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.host }}
  labels:
    app: {{ .Values.mysql.host }}
spec:
  ports:
    - port: {{ .Values.mysql.servicePort }}
      targetPort: {{ .Values.mysql.containerPort }}
      protocol: TCP
  selector:
    app: {{ .Values.mysql.host }}

