apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-inventory-service
  labels:
    app: inventory-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.app.servicePort }}
      targetPort: {{ .Values.app.containerPort }}
      protocol: TCP
  selector:
    app: inventory-service

