/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.readrealm.order.event;
@org.apache.avro.specific.AvroGenerated
public enum InventoryStatus implements org.apache.avro.generic.GenericEnumSymbol<InventoryStatus> {
  IN_STOCK, OUT_OF_STOCK, PROCESSING, NOT_FOUND  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"InventoryStatus\",\"namespace\":\"com.readrealm.order.event\",\"symbols\":[\"IN_STOCK\",\"OUT_OF_STOCK\",\"PROCESSING\",\"NOT_FOUND\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
