apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels:
    app: {{ .Values.name }}
data:
  KAFKA_KRAFT_MODE: "true"
  KAFKA_PROCESS_ROLES: "controller,broker"
  KAFKA_NODE_ID: "{{ .Values.broker.id }}"
  KAFKA_CONTROLLER_QUORUM_VOTERS: "{{ .Values.broker.id }}@{{ .Values.name }}-{{ .Values.broker.id }}.{{ .Values.name }}.{{ .Release.Namespace }}.svc.cluster.local:9093"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://{{ .Values.name }}-{{ .Values.broker.id }}.{{ .Values.name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.ports.plaintext }}"
  KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:{{ .Values.ports.plaintext }},CONTROLLER://0.0.0.0:{{ .Values.ports.controller }}"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
  KAFKA_LOG_DIRS: "/var/lib/kafka/data"
  KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_LOG_RETENTION_HOURS: "168"
  KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"
  CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDM2Qk"