services:
  mongodb:
    image: mongo:latest
    container_name: payments_mongodb
    ports:
      - "27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./data/mongodb:/data/db
