apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels:
    app: {{ .Release.Name }}-keycloak
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  KC_DB: "mysql"
  KC_DB_URL: jdbc:mysql://{{ .Release.Name }}-keycloak-mysql:3306/keycloak
  KC_DB_USERNAME: "keycloak"
  KC_DB_PASSWORD: "password"
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin"