apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels:
    app: {{ .Values.name }}
data:
  KC_DB: {{ .Values.database.provider | quote }}
  KC_DB_URL: "jdbc:{{ .Values.database.provider }}://{{ .Values.database.name }}:{{ .Values.database.service.port }}/{{ .Values.database.auth.database }}"
  KC_DB_USERNAME: {{ .Values.database.auth.username | quote }}
  KC_DB_PASSWORD: {{ .Values.database.auth.password | quote }}
  KEYCLOAK_ADMIN: {{ .Values.admin.username | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.admin.password | quote }}