apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "start-dev"
            - "--import-realm"
          envFrom:
            - configMapRef:
                name: {{ .Values.configmap.name }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          {{- if .Values.volumes.realms.enabled }}
          volumeMounts:
            - name: realms-volume
              mountPath: {{ .Values.volumes.realms.mountPath }}
          {{- end }}
      {{- if .Values.volumes.realms.enabled }}
      volumes:
        - name: realms-volume
          configMap:
            name: {{ .Values.volumes.realms.configmapName }}
      {{- end }}