{{- if .Values.database.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.database.name }}
  labels:
    app: {{ .Values.database.name }}
spec:
  serviceName: {{ .Values.database.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.database.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.database.name }}
    spec:
      containers:
        - name: {{ .Values.database.name }}
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.database.auth.rootPassword | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.database.auth.database | quote }}
            - name: MYSQL_USER
              value: {{ .Values.database.auth.username | quote }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.database.auth.password | quote }}
          ports:
            - name: mysql
              containerPort: {{ .Values.database.service.port }}
              protocol: TCP
          volumeMounts:
            - name: mysql-data
              mountPath: {{ .Values.database.persistence.mountPath }}
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
        labels:
          app: {{ .Values.database.name }}
      spec:
        accessModes:
          - {{ .Values.database.persistence.accessMode }}
        {{- if .Values.database.persistence.storageClass }}
        storageClassName: {{ .Values.database.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.database.persistence.size }}
{{- end }}