{{- if .Values.mysql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-keycloak-mysql
  labels:
    app: {{ .Release.Name }}-keycloak-mysql
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: {{ .Release.Name }}-keycloak-mysql
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-keycloak-mysql
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-keycloak-mysql
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: mysql
          image: "{{ .Values.mysql.image.repository }}:{{ .Values.mysql.image.tag }}"
          imagePullPolicy: {{ .Values.mysql.image.pullPolicy }}
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: {{ .Values.mysql.auth.rootPassword | quote }}
            - name: MYSQL_DATABASE
              value: {{ .Values.mysql.auth.database | quote }}
            - name: MYSQL_USER
              value: {{ .Values.mysql.auth.username | quote }}
            - name: MYSQL_PASSWORD
              value: {{ .Values.mysql.auth.password | quote }}
          ports:
            - name: mysql
              containerPort: {{ .Values.mysql.service.port }}
              protocol: TCP
          volumeMounts:
            - name: mysql-data
              mountPath: {{ .Values.mysql.persistence.mountPath }}
  volumeClaimTemplates:
    - metadata:
        name: mysql-data
        labels:
          app: {{ .Release.Name }}-mysql
          release: {{ .Release.Name }}
      spec:
        accessModes:
          - {{ .Values.mysql.persistence.accessMode }}
        {{- if .Values.mysql.persistence.storageClass }}
        storageClassName: {{ .Values.mysql.persistence.storageClass }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.mysql.persistence.size }}
{{- end }}