apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels:
    app: {{ .Values.name }}
data:
  SCHEMA_REGISTRY_HOST_NAME: "schema-registry"
  SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "PLAINTEXT://{{ .Values.kafka.name }}-{{ .Values.kafka.broker.id }}.{{ .Values.kafka.name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.kafka.port }}"
  SCHEMA_REGISTRY_LISTENERS: "http://0.0.0.0:{{ .Values.service.targetPort }}"
