apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
data:
  APP_NAME: {{ .Values.app.name | quote }}
  SERVER_PORT: {{ .Values.app.containerPort | quote }}
  VIRTUAL_THREADS_ENABLED: "true"
  SWAGGER_PATH: "/swagger-ui.html"
  API_DOCS_PATH: "/v1/api-docs"
  DOCS_TITLE: "Notification Service"
  DOCS_VERSION: "1.0"
  MANAGEMENT_EXPOSE: "health, info, metrics, prometheus"
  PERCENTILES_HISTOGRAM: "true"
  SAMPLING_PROBABILITY: "1.0"

  # Kafka Configuration
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "{{ .Values.kafka.name }}-{{ .Values.kafka.broker.id }}.{{ .Values.kafka.service.name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.kafka.service.port }}"
  SPRING_KAFKA_CONSUMER_GROUP_ID: "notification-Service"
  SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER: "org.apache.kafka.common.serialization.StringDeserializer"
  SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER: "org.springframework.kafka.support.serializer.ErrorHandlingDeserializer"
  SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_DESERIALIZER_KEY_DELEGATE_CLASS: "org.apache.kafka.common.serialization.StringDeserializer"
  SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_DESERIALIZER_VALUE_DELEGATE_CLASS: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
  SPRING_KAFKA_CONSUMER_PROPERTIES_SCHEMA_REGISTRY_URL: "http://{{ .Values.schemaRegistry.service.name }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.schemaRegistry.service.port }}"
  SPRING_KAFKA_CONSUMER_PROPERTIES_SPECIFIC_AVRO_READER: "true"

  # Mail Configuration
  SPRING_MAIL_HOST: {{ .Values.mail.host | quote }}
  SPRING_MAIL_PORT: {{ .Values.mail.port | quote }}
  SPRING_MAIL_USERNAME: {{ .Values.mail.username | quote }}
  SPRING_MAIL_PASSWORD: {{ .Values.mail.password | quote }}
  SPRING_MAIL_PROTOCOL: {{ .Values.mail.protocol | quote }}
  SPRING_MAIL_TEST_CONNECTION: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_CONNECTIONTIMEOUT: "5000"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_TIMEOUT: "5000"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_WRITETIMEOUT: "5000"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "PLAIN"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS: "Optional"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_ENABLE: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_SSL_TRUST: {{ .Values.mail.host | quote }}

  # Monitoring Configuration
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health, info, metrics, prometheus"
  MANAGEMENT_METRICS_DISTRIBUTION_PERCENTILES-HISTOGRAM_HTTP_SERVER_REQUESTS: "true"
  MANAGEMENT_OBSERVATIONS_KEY_VALUES_APPLICATION: "notification-service"
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: {{ .Values.monitoring.sampling.probability | quote }}
