apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.name }}
  labels:
    app: {{ .Values.mongodb.name }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.mongodb.servicePort }}
      targetPort: {{ .Values.mongodb.containerPort }}
      protocol: TCP
  selector:
    app: {{ .Values.mongodb.name }}

