version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: catalog-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: catalog-db
    ports:
      - "3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
  redis:
    image: redis:7.2.0
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/var/lib/redis