# Default values for schema-registry

replicaCount: 1

name: schema-registry

image:
  repository: confluentinc/cp-schema-registry
  tag: 7.5.0
  pullPolicy: IfNotPresent

service:
  port: 8081
  targetPort: 8081


kafka:
  enabled: true
  name: kafka
  port: 9092
  broker:
    id: 0


configmap:
    name: schema-registry-config