apiVersion: v1
kind: Service
metadata:
  name: catalog-service
spec:
  ports:
    - port: {{ .Values.app.servicePort }}
      targetPort: {{ .Values.app.containerPort }}
  selector:
    app: catalog-service
