apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
  labels:
    app: {{ .Values.app.name }}
data:
  APP_NAME: {{ .Values.app.name | quote }}
  SERVER_PORT: {{ .Values.app.containerPort | quote }}
  DATASOURCE_URL: "jdbc:mysql://{{ .Values.database.name }}:{{ .Values.database.servicePort }}/{{ .Values.database.database }}"
  DATABASE_USERNAME: "root"
  DATABASE_PASSWORD: {{ .Values.database.rootPassword | quote }}
  DATABASE_DRIVER: "com.mysql.cj.jdbc.Driver"
  JPA_DDL_AUTO: "none"
  JPA_SHOW_SQL: "true"
  VIRTUAL_THREADS_ENABLED: "true"
  CACHE_DURATION: "1"
  REDIS_HOST: {{ .Values.cache.name | quote }}
  REDIS_PORT: {{ .Values.cache.servicePort | quote }}
  SWAGGER_PATH: "/swagger-ui.html"
  API_DOCS_PATH: "/v1/api-docs"
  DOCS_TITLE: "Catalog Service"
  DOCS_VERSION: "1.0"
  MANAGEMENT_EXPOSE: "health, info, metrics, prometheus"
  PERCENTILES_HISTOGRAM: "true"
  SAMPLING_PROBABILITY: "1.0"
