apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.name }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.mysql.servicePort }}
      targetPort: {{ .Values.mysql.containerPort }}
  selector:
    app: {{ .Values.mysql.name }}