apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.database.name }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.database.servicePort }}
      targetPort: {{ .Values.database.containerPort }}
  selector:
    app: {{ .Values.database.name }}