apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.cache.name }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.cache.servicePort }}
      targetPort: {{ .Values.cache.containerPort }}
  selector:
    app: {{ .Values.cache.name }}
