apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.name }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.redis.servicePort }}
      targetPort: {{ .Values.redis.containerPort }}
  selector:
    app: {{ .Values.redis.name }}
