apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.cache.name | quote }}
spec:
  serviceName: {{ .Values.cache.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.cache.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.cache.name }}
    spec:
      containers:
        - name: {{ .Values.cache.name }}
          image: {{ .Values.cache.image }}
          ports:
            - containerPort: {{ .Values.cache.containerPort }}
          volumeMounts:
            - name: redis-data
              mountPath: /var/lib/redis
  volumeClaimTemplates:
    - metadata:
        name: redis-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi