version: '4'
services:
  mysql:
    image: mysql:8.3.0
    container_name: inventory-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory-db
    ports:
      - "3306"
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: