# Default values for kafka

replicaCount: 1

image:
  repository: confluentinc/cp-kafka
  tag: latest
  pullPolicy: IfNotPresent

service:
  ports:
    - name: plaintext
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: internal
      port: 29092
      targetPort: 29092
      protocol: TCP
    - name: controller
      port: 9093
      targetPort: 9093
      protocol: TCP

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

# ConfigMap for Kafka configuration
configMap:
  name: kafka-config

# Persistence configuration
persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 8Gi
  mountPath: /var/lib/kafka/data

broker:
  id: 0