# Default values for kafka

replicaCount: 1

name: kafka

image:
  repository: confluentinc/cp-kafka
  tag: latest
  pullPolicy: IfNotPresent

service:
  ports:
    - name: plaintext
      port: 9092
      targetPort: 9092
      protocol: TCP
    - name: internal
      port: 29092
      targetPort: 29092
      protocol: TCP
    - name: controller
      port: 9093
      targetPort: 9093
      protocol: TCP

ports:
  plaintext: 9092
  internal: 29092
  controller: 9093

# ConfigMap for Kafka configuration
configmap:
  name: kafka-config

# Persistence configuration
persistence:
  name: kafka-data
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 8Gi
  mountPath: /var/lib/kafka/data

broker:
  id: 0