services:
  mongodb:
    image: mongo:7.0.0
    container_name: order_mongodb
    ports:
      - "27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./data/mongodb:/data/db