server:
  port: 9090

spring:
  application:
    name: gateway-service
  docker:
    compose:
      file: Gateway Service\\docker-compose.yaml
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8181/realms/readrealm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: readrealm
            client-secret: rytEJWsrvgeNcWN9JWai6UuEW075myeE
            redirect-uri: http://localhost:9090/login/oauth2/code/readrealm
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
            - StripPrefix=1

        - id: order-service-api-docs
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/docs/order-service/v1/api-docs
          filters:
            - StripPrefix=2
            - RemoveRequestHeader=Cookie

        - id: catalog-service
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/api/v1/books/**, /api/v1/authors/**, /api/v1/categories/**, /api/v1/refresh/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
            - StripPrefix=1

        - id: order-service-api-docs
          uri: lb://CATALOG-SERVICE
          predicates:
            - Path=/docs/catalog-service/v1/api-docs
          filters:
            - StripPrefix=2
            - RemoveRequestHeader=Cookie


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Order Service
        url: /docs/order-service/v1/api-docs
      - name: Catalog Service
        url: /docs/catalog-service/v1/api-docs
  api-docs:
    path: /v1/api-docs
