server:
  port: 9090

spring:
  application:
    name: gateway-service
  docker:
    compose:
      file: Gateway Service\\docker-compose.yaml
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8181/realms/readrealm
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: readrealm
            client-secret: rytEJWsrvgeNcWN9JWai6UuEW075myeE
            redirect-uri: http://localhost:9090/login/oauth2/code/readrealm
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: order-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/orders/**
          filters:
            - StripPrefix=1
            - TokenRelay=
            - RemoveRequestHeader=Cookie
            - name: CircuitBreaker
              args:
                name: orderServiceCircuitBreaker
                fallbackUri: forward:/fallback/order-service

        - id: order-service-api-docs
          uri: http://localhost:8081
          predicates:
            - Path=/docs/order-service/v1/api-docs
          filters:
            - StripPrefix=2
            - RemoveRequestHeader=Cookie

        - id: catalog-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/books/**, /api/v1/authors/**, /api/v1/categories/**, /api/v1/refresh/**
          filters:
            - StripPrefix=1
            - TokenRelay=
            - RemoveRequestHeader=Cookie
            - name: CircuitBreaker
              args:
                name: catalogServiceCircuitBreaker
                fallbackUri: forward:/fallback/catalog-service

        - id: catalog-service-api-docs
          uri: http://localhost:8080
          predicates:
            - Path=/docs/catalog-service/v1/api-docs
          filters:
            - StripPrefix=2
            - RemoveRequestHeader=Cookie


resilience4j:
  circuitbreaker:
    instances:
      orderServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: false
        minimumNumberOfCalls: 5
        timeout-duration: 3s
      catalogServiceCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: false
        minimumNumberOfCalls: 5
        timeout-duration: 3s
  retry:
    instances:
      orderServiceCircuitBreaker:
        max-attempts: 3
        wait-duration: 2s
      catalogServiceCircuitBreaker:
        max-attempts: 3
        wait-duration: 2s


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Order Service
        url: /docs/order-service/v1/api-docs
      - name: Catalog Service
        url: /docs/catalog-service/v1/api-docs
  api-docs:
    path: /v1/api-docs
