mysql:
  host: catalog-mysql
  image: mysql:8.3.0
  servicePort: 3306
  containerPort: 3306
  database: catalog-db
  rootPassword: root

redis:
  host: catalog-redis
  image: redis:7.2.0
  servicePort: 6379
  containerPort: 6379

app:
  image: hazemkh98/catalog-service:1.0.2
  servicePort: 8080
  containerPort: 8080


volumes:
  mysqlData: /data/mysql
  redisData: /data/redis
