database:
  name: catalog-mysql
  image: mysql:8.3.0
  servicePort: 3306
  containerPort: 3306
  applicationDatabaseName: catalog-db
  rootPassword: root

cache:
  name: catalog-redis
  image: redis:7.2.0
  servicePort: 6379
  containerPort: 6379

app:
  name: catalog-service
  image: hazemkh98/catalog-service:1.0.2
  servicePort: 8080
  containerPort: 8080


volumes:
  mysqlData: /data/mysql
  redisData: /data/redis

configmap:
  name: catalog-config
